### PR TITLE
Simplified data tracker access and improved compatibility

### PR DESCRIPTION
**Pull request by Nillo-Code**
Prompted from https://github.com/samolego/Taterzens/issues/132 mod compatibility issue.

With the existing pattern `SPELL_ENGINE_SYNCED_EFFECTS` was causing an id collision. By extending `Entity` and directly accessing the data tracker, rather than casting `this` and using methods, the issue was resolved

### CODE REVIEW

**Comment by ZsoltMolnarrr** [comment]
This PR seems to solve the issue in a deterministic way.
I still don't understand why. Maybe the conflicting mod overrides the `getDataTracker` method hence direct access helps.

After testing it looks like this change has no negative effect.
Thank you for the contribution!

**Comment by samolego** [comment]
Yeah, Taterzens do override getDataTracker due to serveside mod syncing ... Wasn't really aware it'd cause issues

**Comment by RockZe** [comment]
hah, after reading this report, I didn't understand anything 😅
As far as I understand, an ordinary user cannot solve this problem, and you need to dig deeper and change the mod/mods itself?

**Comment by ZsoltMolnarrr** [comment]
The fix will be published within a few days. :)

**Comment by DEAFG0AT** [comment]
> The fix will be published within a few days. :)

Hey, I'm still having this error on 1.19.2! Did this fix ever get published?
My Spell Engine version is 0.9.25 and Taterzen's is 1.11.1

**Comment by Nillo-Code** [comment]
I can confirm that it has been published and is working with the latest versions, are you sure it is these mods causing the issue?

**Comment by ZsoltMolnarrr** [comment]
The fix has been published long time months ago.
We even figured out why it is working. Tatarzen seemd to override some method.

**Pull request merged**
