### PR TITLE
Add more events, make Spell Book creation more flexible.

### PR DESCRIPTION
**Pull request by Karashok-Leo**
Add more events.
Make Spell Book creation more flexible.
I am a new modder. If there is anything bad, please point it out.🥹

### CODE REVIEW

**Comment by ZsoltMolnarrr** [comment]
What is a practical usecase for these changes in the game?

**Comment by Karashok-Leo** [comment]
> What is a practical usecase for these changes in the game?

For example, when a spell projectile collides with a block or entity, it interacts with the world, causing an explosion, or placing some blocks, or other game mechanisms. The onSpellImpact event is also for the same purpose. 

Besides, I wrote a subclass of SpellbookItem (to override the methods in Trinket), but found that there is no applicable registration method in the Spellbooks class...

**Comment by ZsoltMolnarrr** [comment]
What is the purpose of spell book creation related changes?

Are you familiar with spell container assignment being able to make any item into spell bindable?

**Comment by Karashok-Leo** [comment]
I have a MySpellBookItem class that extends the SpellBookTrinketItem class.
In this case, how can I register a MySpellBookItem using only the methods provided here?

**Pull request closed without merging**
